articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

todaymovie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todaymovieapp.views import main

urlpatterns = [
    path('', main, name='home'),

    path('admin/', admin.site.urls),
    path('todaymovies/', include('todaymovieapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todaymovieapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from todaymovieapp.views import main, TodaymovieCreateView, TodaymovieDetailView, TodaymovieUpdateView, TodaymovieDeleteView

app_name = "todaymovieapp"

urlpatterns = [
    path('main/', main, name='main'),

    path('login/', LoginView.as_view(template_name='todaymovieapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', TodaymovieCreateView.as_view(), name='create'),
    path('detail/<int:pk>', TodaymovieDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TodaymovieUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TodaymovieDeleteView.as_view(), name='delete'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_created=True, null=True)

todaymovieapp/models.py
from django.db import models

# Create your models here.

class todaymovie(models.Model):
    text = models.CharField(max_length=255, null=False)

todaymovieapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class TodaymovieUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

todaymovieapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render


# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from todaymovieapp.decorators import todaymovie_ownership_required
from todaymovieapp.forms import TodaymovieUpdateForm
from todaymovieapp.models import todaymovie

has_ownership = [todaymovie_ownership_required, login_required]

def main(request):
    if request.method == "POST":
        temp = request.POST.get('main_input')
        new_main = todaymovie()
        new_main.text = temp
        new_main.save()

        return HttpResponseRedirect(reverse('todaymovie:main'))
    else:
        main_list = todaymovie.objects.all()
        return render(request, 'todaymovieapp/main.html', context={'main_list': main_list})

class TodaymovieCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('todaymovieapp:main')
    template_name = 'todaymovieapp/create.html'

class TodaymovieDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'todaymovieapp/detail.html'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(TodaymovieDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class TodaymovieDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('todaymovieapp:login')
    template_name = 'todaymovieapp/delete.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class TodaymovieUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = TodaymovieUpdateForm
    success_url = reverse_lazy('todaymovieapp:main')
    template_name = 'todaymovieapp/update.html'

todaymovieapp/templates/todaymovieapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4rem auto">
        <div class="mb-4">
            <h4>회원가입</h4>
        </div>
        <form action="{% url 'todaymovieapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
        </form>
    </div>

{% endblock %}

todaymovieapp/templates/todaymovieapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4rem auto">
        <div class="mb-4">
            <h4>계정을 삭제하시겠습니까 ?</h4>
        </div>
        <form action="{% url 'todaymovieapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-4 mt-3">
        </form>
    </div>

{% endblock %}

todaymovieapp/templates/todaymovieapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 400px; margin: 4rem auto">

            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt=""
                 style="height: 10rem; width: 10rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">

            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}
                {% if target_user == user %}
                <a class="material-icons"
                   style="margin-left: 6px; box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .2rem;"
                   href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    edit
                </a>
                {% endif %}
            </h2>
            <h5 style="margin-bottom: 3rem;">
                {{ target_user.profile.message }}
            </h5>
            {% else %}
                {% if target_user == user %}

                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">
                        프로파일 생성
                    </h2>
                </a>
                {% else %}
                    <h2>
                        닉네임 미설정
                    </h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
            <a class="material-icons"
               style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .2rem;"
               href="{% url 'todaymovieapp:update' pk=user.pk %}">
                    settings
            </a>
            <a class="material-icons"
               style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .2rem;"
               href="{% url 'todaymovieapp:delete' pk=user.pk %}">
                    cancel
            </a>
            {% endif %}

        </div>
        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>

{% endblock %}

todaymovieapp/templates/todaymovieapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4rem auto">
        <div style="margin-bottom: 2rem">
            <h4>로그인</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
            </form>
        </div>
    </div>


{% endblock %}

todaymovieapp/templates/todaymovieapp/main.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}

    <div style="height: 300px; text-align: center">

        <form action="" method="get">
        <input style="height: 40px; width: 400px; border-radius: 30px;"
               type="search" placeholder=" 검색" name="keyword">
  </form>

    </div>

{% endblock %}

todaymovieapp/templates/todaymovieapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 400px; margin: 4rem auto">
        <div class="mb-4">
            <h4>정보변경</h4>
        </div>
        <form action="{% url 'todaymovieapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
        </form>
    </div>

{% endblock %}